services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web-log
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  php:
    build: ./php
    restart: always
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ..:/app
      - ./php/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./certs:/app/certs
    tty: true

volumes:
  db_data: